### PR TITLE
[ISSUE 114] Fixed bug in updateSynapsesWeightsDevice

### LINKED ISSUE #114: Fix problem in updateSynapsesWeightsDevice
This is a fix that was incorporated into the BrainGrid repo in the master branch at commit [ee530847b997d3cbaaee689b9500c679699787e8](https://github.com/UWB-Biocomputing/BrainGrid/commit/ee530847b997d3cbaaee689b9500c679699787e8), but apparently not in the single-threaded-master branch.

### PR DESCRIPTION
**Pull request by jardiamj**
Closes #114 

Fixed bug in updateSynapsesWeightsDevice where a synapse between the same neuron could be created.

### CODE REVIEW

File: Simulator/Connections/Neuro/ConnGrowth.cpp [hunk 1]
```diff
@@ -240,6 +240,11 @@ void ConnGrowth::updateSynapsesWeights()
    for (int srcVertex = 0; srcVertex < numVertices; srcVertex++) {
       // and each destination neuron 'b'
       for (int destVertex = 0; destVertex < numVertices; destVertex++) {
+         if (destVertex == srcVertex) {
+            // we don't create a synapse between the same neuron
+            continue;
+         }
```
Comment (stiber) [inline Simulator/Connections/Neuro/ConnGrowth.cpp:246]: Hmm. I wonder how this issue crept in...

**Review by stiber — APPROVED** [review]
