### PR TITLE
Fix parameter manager

### LINKED ISSUE #208: ParameterManager error messages produced during at least some simulator runs
We get the following error messages when running `test-tiny.xml` and `test-small.xml`. Might be true for other config files:

```
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
```

### PR DESCRIPTION
**Pull request by jbrown725**
closes #208

### CODE REVIEW

File: Simulator/Utils/ParameterManager.cpp [hunk 1]
```diff
@@ -100,13 +100,17 @@ bool ParameterManager::checkDocumentStatus() {
...
    if (!checkDocumentStatus()) return false;
-   if (!TinyXPath::o_xpath_string(root_, xpath.c_str(), xpath)) {
+
+   // temp string holds evaluation of value at xpath
+   string temp;
+   // raise error if tinyxml cannot compute the xpath's value or returns empty
+   if (!TinyXPath::o_xpath_string(root_, xpath.c_str(), temp) || temp == "") {
       cerr << "Failed loading simulation parameter for xpath "
            << xpath << endl;
       // TODO: possibly get better error information?
```
Comment (stiber) [inline Simulator/Utils/ParameterManager.cpp:110]: Is this possible?

File: configfiles/test-large-connected.xml [hunk 2]
```diff
@@ -80,5 +92,10 @@
         <probedNListFileName name="prbNListFileName" type="InputFile"/>
       </LayoutFiles>
     </LayoutParams>
+
+    <RecorderParams class="XmlGrowthRecorder" name="RecorderParams">
+      <probedNListFileName name="prbNListFileName" type="InputFile">../configfiles/NList/probedNList_900.xml</probedNListFileName>
```
Comment (stiber) [inline configfiles/test-large-connected.xml:97]: I think this file is for a 900-neuron (30x30) simulation. We can talk about this at our upcoming meeting. I'll not comment on the other config files.

**Review by stiber — COMMENTED** [review]
I think there's just two matters remaining for us to discuss in this:

1. Double-check some things in the config files (I think just the probed neuron list files, but maybe not).
2. What exactly are the PM error messages that these mods are producing and do they include as much information as possible (I believe it's file line and column number)? This is mostly spurred by a "TODO" comment still in the code.

**Review by stiber — APPROVED** [review]
