### PR TITLE
Factory cleanup

### LINKED ISSUE #361: Clean up code of factory classes
All factory classes have a map with key names associated with a pointer to the create method of a given class. Currently, the create method loops through the map data structure to find the correct class; this is unnecessary and unexpected since you can access the class name from a map using `find`.

These classes should be changed to use `find`, if nothing else it would make the code easier to read.

### PR DESCRIPTION
**Pull request by jardiamj**
Closes #361.

I did some cleaned up of the various factory classes. If nothing else, this should improve readability.

Summary:

- Switched to using `find`, instead of looping over the `createFunctions` map.
- Changed `noiseRNG` from a naked pointer to a `shared_ptr`.
- Removed not needed class member pointer to the instance created by the factory.
- Wrote Unit Tests for all factory classes.
- Fixed Segmentation fault on destruction of `Connections911` class (revealed by the unit tests).

### CODE REVIEW

File: Simulator/Utils/Global.h [hunk 1]
```diff
@@ -65,6 +64,7 @@ typedef unsigned long long int uint64_t;   //included in inttypes.h, which is no
    //#include "Norm.h"
    #include "Coordinate.h"
    #include "VectorMatrix.h"
+   #include "memory"
```
Comment (stiber) [inline Simulator/Utils/Global.h:67]: Should this be `#include <memory>`?

Comment (jardiamj) [reply Simulator/Utils/Global.h]: Fixed. It is odd that both include forms work and point to the same file.

**Comment by jardiamj** [comment]
Can we merge this?

**Review by stiber — APPROVED** [review]

**Comment by stiber** [comment]
Sorry for the slow response time...
